### ISSUE TITLE
Error message when loading AddressBook.jar

### ISSUE THREAD

**Issue by WinstonJin** [nus-cs2103-AY2425S1/forum#139]
When I follow the steps on the CS2103 website on opening AddressBook, I get an error at step 4

Here is the instructions from the CS2103 website:

Quick start
1. Ensure you have Java 17 or above installed in your Computer.

2. Download the latest .jar file from [here](https://github.com/se-edu/addressbook-level3/releases).

3. Copy the file to the folder you want to use as the home folder for your AddressBook.

4. Open a command terminal, cd into the folder you put the jar file in, and use the java -jar addressbook.jar command to run the application.
A GUI similar to the below should appear in a few seconds. Note how the app contains some sample data.

Here is the error code from terminal:

Aug 30, 2024 5:12:40 PM seedu.address.Main main
WARNING: The warning about Unsupported JavaFX configuration below (if any) can be ignored.
Aug 30, 2024 5:12:40 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2d4e282b'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib: dlopen(/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib, 0x0001): tried: '/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib' (no such file), '/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
java.lang.UnsatisfiedLinkError: /Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib: dlopen(/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib, 0x0001): tried: '/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib' (no such file), '/Users/winston/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404)
	at java.base/java.lang.Runtime.load0(Runtime.java:817)
	at java.base/java.lang.System.load(System.java:2015)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:391)
	at java.base/java.lang.Class.forName(Class.java:382)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by damithc** [comment]
@WinstonJin possibly related issues https://github.com/nus-cs2103-AY2425S1/forum/issues?q=is%3Aissue+UnsatisfiedLinkError+is%3Aclosed
