### ISSUE TITLE
Warning in console - javafx.fxml.LoadException: Root value already specified.

### ISSUE THREAD

**Issue by anselmlong** [nus-cs2103-AY2425S1/forum#226]
Not sure where this error is coming from, but here's the stack trace:
```
Sep 06, 2024 3:35:35 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ef1a59a'
javafx.fxml.LoadException: Root value already specified.
/C:/Users/ansel/ip/build/resources/main/view/MainWindow.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2710)
	at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2893)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2842)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2523)
	at sigma.gui.MainWindow.<init>(MainWindow.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:939)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2845)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2523)
	at sigma.gui.Main.start(Main.java:23)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

I'm using Intellij on Windows. I've got this error ever since I implemented my GUI, but it didn't stop my program from running so I didn't think it was an issue. However, I would like to solve it. Here's my MainWindow.java code, the function part.
``` java
public MainWindow() {
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/view/MainWindow.fxml"));
        fxmlLoader.setRoot(this); // Set the root
        fxmlLoader.setController(this); // Set the controller, optional if it's already set in FXML
        try {
            fxmlLoader.load(); // Load the FXML file
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```
And my MainWindow.fxml:
``` fxml
<AnchorPane xmlns:fx="http://javafx.com/fxml/1"
            maxHeight="-Infinity"
            maxWidth="-Infinity"
            minHeight="-Infinity"
            minWidth="-Infinity"
            prefHeight="600.0"
            prefWidth="400.0"
            stylesheets="@../css/main.css"
            xmlns="http://javafx.com/javafx/17.0.7"
            fx:controller="sigma.gui.MainWindow">
    <children>
        <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0"
                   promptText="Enter a prompt..." AnchorPane.bottomAnchor="1.0" AnchorPane.leftAnchor="0.0"
                   AnchorPane.rightAnchor="76.0"/>
        <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput"
                prefHeight="41.0" prefWidth="76.0" text="Send" textAlignment="CENTER"
                AnchorPane.bottomAnchor="0.6666666666666643" AnchorPane.rightAnchor="0.0"/>
        <ScrollPane fx:id="scrollPane" fitToWidth="true" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0"
                    prefWidth="400.0" vvalue="1.0" AnchorPane.bottomAnchor="42.66666666666663"
                    AnchorPane.leftAnchor="0.0" AnchorPane.rightAnchor="0.0" AnchorPane.topAnchor="0.0">
            <content>
                <VBox fx:id="dialogContainer" prefHeight="552.0" prefWidth="388.0"/>
            </content>
        </ScrollPane>
    </children>
</AnchorPane>
```

Any help would be appreciated! Thank you!

**Comment by Incogdino** [comment]
If my understanding is right on how JavaFX works, there is no need to set the root of `MainWindow` since it have been implicitly defined with `AnchorPane` in your `MainWindow.fxml`. Trying to set the root and controller again is why you are getting the error saying that the root value have already been defined.

To resolve this issue, you can simply delete the `MainWindow` constructor. Let me know if this solves your issue 😄

**Comment by anselmlong** [comment]
Hi! Thanks a lot, that fixed one error message, but turns out there's another? I guess they were separate errors, but I have no clue what's causing this as well. Would anyone have any way to point me in the right direction here?

```
Sep 06, 2024 11:24:59 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5a10114'
```

**Comment by Incogdino** [comment]
I believe we can ignore that error as stated in the last section of the JavaFX tutorial page [here](https://se-education.org/guides/tutorials/javaFxPart1.html#writing-your-first-java-fx-program)

**Comment by Incogdino** [comment]
Just came across #211 . You can try using the solution suggested there to resolve the issue.

**Comment by anselmlong** [comment]
@Incogdino Thanks for the help! That fixed it!
