### ISSUE TITLE
Unable to run Jar file but it works with ./gradlew run in Intellij

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#262]
It works with ./gradlew run in intellij and can be packed into jar file with ./gradlew clean shadowJar but when I run the Jar file with terminal it shows these errors:

initially I suspect that it might due to the incorrect set up of file path within the Main.java 
```
FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));
```
but I put the MainWindow.fxml in the directory as: src\main\resources\view\MainWindow.fxml, so I'm not sure how to fix this error.

```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @552e79fc'
elysia.txt already exists
jar:file:/C:/Users/User/Documents/GitHub/ip/build/libs/elysia.jar!/view/MainWindow.fxml
javafx.fxml.LoadException:
file:/C:/Users/User/Documents/GitHub/ip/build/libs/elysia.jar!/view/MainWindow.fxml:9

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2714)
        at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:944)
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
        at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2845)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2523)
        at elysia.Main.start(Main.java:26)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:939)
        ... 17 more
Caused by: java.lang.NullPointerException: Input stream must not be null
        at javafx.scene.image.Image.validateInputStream(Image.java:1137)
        at javafx.scene.image.Image.<init>(Image.java:704)
        at elysia.MainWindow.<init>(MainWindow.java:27)
        ... 23 more
```

**Comment by C5hives** [comment]
Your error might be related to the application failing to find the image files specified to be displayed. Perhaps your image files got renamed or moved to a new location?

This is my current implementation for loading the image files into the `Image` object.
```
private final Image botImage = new Image(this.getClass().getResourceAsStream("/images/lawrence.jpg"));
```
If I rename the image file's address to:
```
// changed to a .png file
private final Image botImage = new Image(this.getClass().getResourceAsStream("/images/lawrence.png"));
```

I encounter the same error as you as `lawrence.png` does not exist.
```
Caused by: java.lang.NullPointerException: Input stream must not be null
        at javafx.scene.image.Image.validateInputStream(Image.java:1137)
        at javafx.scene.image.Image.<init>(Image.java:704)
        at lawrence.ui.components.MainWindow.<init>(MainWindow.java:29)
        ... 23 more
```
However, it should be noted that I am unable to run `gradlew run` successfully when I encounter this error. If your image files were specified correctly, your issue is likely to stem from something else.

**Comment by Elinengu** [comment]
> Your error might be related to the application failing to find the image files specified to be displayed. Perhaps your image files got renamed or moved to a new location?
> 
> This is my current implementation for loading the image files into the `Image` object.
> 
> ```
> private final Image botImage = new Image(this.getClass().getResourceAsStream("/images/lawrence.jpg"));
> ```
> 
> If I rename the image file's address to:
> 
> ```
> // changed to a .png file
> private final Image botImage = new Image(this.getClass().getResourceAsStream("/images/lawrence.png"));
> ```
> 
> I encounter the same error as you as `lawrence.png` does not exist.
> 
> ```
> Caused by: java.lang.NullPointerException: Input stream must not be null
>         at javafx.scene.image.Image.validateInputStream(Image.java:1137)
>         at javafx.scene.image.Image.<init>(Image.java:704)
>         at lawrence.ui.components.MainWindow.<init>(MainWindow.java:29)
>         ... 23 more
> ```
> 
> However, it should be noted that I am unable to run `gradlew run` successfully when I encounter this error. If your image files were specified correctly, your issue is likely to stem from something else.

Hi!!! Thank you so much this is the issue I encountered as well. After changing the file name it works
