### ISSUE TITLE
Error when running gradlew run. My application cannot start now.

### ISSUE THREAD

**Issue by obrona** [nus-cs2103-AY2425S1/forum#289]
I am getting this error when I run `gradlew run`
```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2a62d1e2'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.NoClassDefFoundError: gui/MainWindow (wrong name: GUI/MainWindow)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:931)
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
        at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2845)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2523)
        at gui.Main.start(Main.java:22)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        ... 1 more
```
I was doing some renaming of my package names, now this happended. Please help guys, my application cannot even start anymore.

**Comment by RezwanAhmed123** [comment]
From what I see in your code, maybe its because ur Main class and your launcher class are not in the same folder. Could you put the Main Class in ur GUI package and update ur build.gradle file to include the relative path of ur launcher class from `mainClass.set("Launcher")` to `mainClass.set("GUI.Launcher")` and try again?

**Comment by obrona** [comment]
I have resolved the error. It was because when I changed the package name, I did not update the name for the fx:controller.
It should be `<fx:controller="gui.MainWindow">` and not `<fx:controller="GUI.MainWindow">`
