### ISSUE TITLE
Help smoke testing my .jar file

### ISSUE THREAD

**Issue by nuagetsu** [nus-cs2103-AY2425S1/forum#335]
I haven't managed to test my jar file on MacOS and Linux environments, and was wondering if anyone could help out. 
You can download the jar file [here](https://github.com/EdaYeo/ip/releases/download/A-Release/Bunbun.jar), and [here's](https://edayeo.github.io/ip/) my user guide.

Thank you!!

**Comment by tata32000** [comment]
@EdaYeo I have tested your app in MacOS and it shows this error when first launch:
```
java.io.FileNotFoundException: data/Bunbun.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.util.Scanner.<init>(Scanner.java:639)
	at bunbun.utils.Storage.toArrayList(Storage.java:98)
	at bunbun.utils.TaskList.<init>(TaskList.java:35)
	at bunbun.Bunbun.<init>(Bunbun.java:26)
	at bunbun.gui.Main.<init>(Main.java:17)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

![Screenshot 2024-09-18 at 20 13 05](https://github.com/user-attachments/assets/dcb1c42d-dcb0-4494-a2a7-c0501bf010f2)


It would be nice if we can unmark the task if the user marks the task as done by accident. Overall, the app looks pretty nice and everything works as intended.

**Comment by wes-w-z-h** [comment]
lgtm 👍Would be nice to have an unmark command!

**Comment by SKarthikeyan28** [comment]
Hi, I am a mac user and the jar file runs well on my mac, but has a similar error thrown at the start on my terminal.
Beyond that, the chatbot runs well.
