### ISSUE TITLE
CI failing with java.io.IOException: Server returned HTTP response code: 500 after merge although PR passes CI

### ISSUE THREAD

**Issue by testing1234567891011121314** [nus-cs2103-AY2425S1/forum#512]
Hi I merged a branch which was passing CI into our team repo, but now it is failing with the error below:

```
Run ./gradlew check coverage
Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
Error: Exception in thread "main" java.io.IOException: Server returned HTTP response code: 500 for URL: https://github.com/gradle/gradle-distributions/releases/download/v7.4.2/gradle-7.4.2-bin.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2034)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1613)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:[8](https://github.com/AY2425S1-CS2103T-T16-1/tp/actions/runs/11329521169/job/31505236574#step:8:9)7)
	at org.gradle.wrapper.Download.download(Download.java:67)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:6[9](https://github.com/AY2425S1-CS2103T-T16-1/tp/actions/runs/11329521169/job/31505236574#step:8:10))
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:[10](https://github.com/AY2425S1-CS2103T-T16-1/tp/actions/runs/11329521169/job/31505236574#step:8:11)7)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Error: Process completed with exit code 1.
```
Anyone has a similar experience? Is it an issue with the server?

PR Passes CI
![image](https://github.com/user-attachments/assets/858fc4b4-99bd-4db6-ac86-db58d1ab70e8)

TP Failing CI 
![image](https://github.com/user-attachments/assets/2a26fe31-f5bc-4b52-a193-58f4a4d318f6)

**Comment by yadobler** [comment]
Please use triple back tick (` ```  `) for code blocks!

**Comment by yadobler** [comment]
Try running the checks again. `HTTP 500` is server related error, probably timed out. It might be a one-off issue

**Comment by damithc** [comment]
> Try running the checks again. `HTTP 500` is server related error, probably timed out. It might be a one-off issue

Yup, when CI fails due to a network related issue, there is always a chance that it was a temporary network issue. In that case, re-running the CI again after a while can fix the problem.

**Comment by testing1234567891011121314** [comment]
Code edited, Thanks for the help!
